data:extend({
  {
    type = "technology",
    name = "kr-advanced-chemistry",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/technologies/advanced-chemistry.png",
    icon_size = 256,
    order = "d-a",
    unit = {
      time = 60,
      count = 275,
      ingredients = {
        { "automation-science-pack", 1 },
        { "logistic-science-pack", 1 },
        { "chemical-science-pack", 1 },
      },
    },
    prerequisites = { "sulfur-processing", "kr-atmosphere-condensation" },
    effects = {
      { type = "unlock-recipe", recipe = "kr-water" },
      { type = "unlock-recipe", recipe = "kr-water-separation" },
      { type = "unlock-recipe", recipe = "ammonia" },
      { type = "unlock-recipe", recipe = "nitric-acid" },
      { type = "unlock-recipe", recipe = "hydrogen-chloride" },
      { type = "unlock-recipe", recipe = "biomethanol" },
    },
  },
  {
    type = "technology",
    name = "kr-air-purification",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/technologies/air-purifier.png",
    icon_size = 256,
    order = "a-e-d",
    unit = {
      time = 45,
      count = 275,
      ingredients = {
        { "automation-science-pack", 1 },
        { "logistic-science-pack", 1 },
        { "chemical-science-pack", 1 },
      },
    },
    prerequisites = { "kr-advanced-chemistry", "engine" },
    effects = {
      { type = "unlock-recipe", recipe = "kr-air-purifier" },
      { type = "unlock-recipe", recipe = "pollution-filter" },
      { type = "unlock-recipe", recipe = "kr-air-cleaning" },
      { type = "unlock-recipe", recipe = "restore-used-pollution-filter" },
    },
  },
  {
    type = "technology",
    name = "kr-atmosphere-condensation",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/technologies/atmospheric-condenser.png",
    icon_size = 256,
    unit = {
      time = 45,
      count = 175,
      ingredients = {
        { "automation-science-pack", 1 },
        { "logistic-science-pack", 1 },
        { "chemical-science-pack", 1 },
      },
    },
    prerequisites = { "kr-fluids-chemistry", "electronics" },
    effects = {
      { type = "unlock-recipe", recipe = "kr-atmospheric-condenser" },
      { type = "unlock-recipe", recipe = "hydrogen" },
      { type = "unlock-recipe", recipe = "oxygen" },
      { type = "unlock-recipe", recipe = "nitrogen" },
      { type = "unlock-recipe", recipe = "water-from-atmosphere" },
    },
  },
  {
    type = "technology",
    name = "kr-enriched-ores",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/technologies/enriched-ores.png",
    icon_size = 256,
    unit = {
      time = 60,
      count = 275,
      ingredients = {
        { "automation-science-pack", 1 },
        { "logistic-science-pack", 1 },
        { "chemical-science-pack", 1 },
      },
    },
    prerequisites = { "kr-advanced-chemistry" },
    effects = {
      { type = "unlock-recipe", recipe = "enriched-iron" },
      { type = "unlock-recipe", recipe = "enriched-copper" },
      { type = "unlock-recipe", recipe = "enriched-rare-metals" },
      { type = "unlock-recipe", recipe = "enriched-iron-plate" },
      { type = "unlock-recipe", recipe = "enriched-copper-plate" },
      { type = "unlock-recipe", recipe = "rare-metals-2" },
      { type = "unlock-recipe", recipe = "dirty-water-filtration-1" },
      { type = "unlock-recipe", recipe = "dirty-water-filtration-2" },
      { type = "unlock-recipe", recipe = "dirty-water-filtration-3" },
    },
  },
  {
    type = "technology",
    name = "kr-lithium-sulfur-battery",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/technologies/lithium-sulfur-battery.png",
    icon_size = 256,
    unit = {
      time = 30,
      count = 200,
      ingredients = {
        { "automation-science-pack", 1 },
        { "logistic-science-pack", 1 },
        { "chemical-science-pack", 1 },
      },
    },
    prerequisites = { "lithium-processing" },
    effects = {
      { type = "unlock-recipe", recipe = "lithium-sulfur-battery" },
    },
  },
  {
    type = "technology",
    name = "kr-radar",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/technologies/radar.png",
    icon_size = 256,
    unit = {
      time = 30,
      count = 200,
      ingredients = {
        { "automation-science-pack", 1 },
        { "logistic-science-pack", 1 },
        { "chemical-science-pack", 1 },
      },
    },
    prerequisites = { "kr-sentinel", "electronics", "steel-processing" },
    effects = {
      { type = "unlock-recipe", recipe = "radar" },
    },
  },
  {
    type = "technology",
    name = "kr-robot-battery",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/technologies/robot-battery.png",
    icon_size = 256,
    unit = {
      time = 30,
      count = 500,
      ingredients = {
        { "automation-science-pack", 1 },
        { "logistic-science-pack", 1 },
        { "chemical-science-pack", 1 },
      },
    },
    prerequisites = { "kr-lithium-sulfur-battery", "robotics" },
    effects = {
      { type = "worker-robot-battery", modifier = 0.4 },
    },
  },
})
