data:extend({
  {
    type = "technology",
    name = "kr-ai-core",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/technologies/ai-core.png",
    icon_size = 256,
    unit = {
      time = 60,
      count = 500,
      ingredients = {
        { "automation-science-pack", 1 },
        { "logistic-science-pack", 1 },
        { "chemical-science-pack", 1 },
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
      },
    },
    prerequisites = { "kr-quarry-minerals-extraction" },
    effects = {
      { type = "unlock-recipe", recipe = "ai-core" },
    },
  },
  {
    type = "technology",
    name = "kr-advanced-radar",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/technologies/advanced-radar.png",
    icon_size = 256,
    unit = {
      time = 60,
      count = 200,
      ingredients = {
        { "automation-science-pack", 1 },
        { "logistic-science-pack", 1 },
        { "chemical-science-pack", 1 },
        { "utility-science-pack", 1 },
      },
    },
    prerequisites = { "kr-radar", "advanced-circuit" },
    effects = {
      { type = "unlock-recipe", recipe = "kr-advanced-radar" },
    },
  },
  {
    type = "technology",
    name = "kr-fusion-energy",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/technologies/fusion-energy.png",
    icon_size = 256,
    unit = {
      time = 60,
      count = 1500,
      ingredients = {
        { "automation-science-pack", 1 },
        { "logistic-science-pack", 1 },
        { "chemical-science-pack", 1 },
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
      },
    },
    prerequisites = {
      "processing-unit",
      "lithium-processing",
      "nuclear-power",
      "utility-science-pack",
      "low-density-structure",
      "kovarex-enrichment-process",
    },
    effects = {
      { type = "unlock-recipe", recipe = "kr-fusion-reactor" },
      { type = "unlock-recipe", recipe = "kr-advanced-steam-turbine" },
      { type = "unlock-recipe", recipe = "heavy-water" },
      { type = "unlock-recipe", recipe = "tritium" },
      { type = "unlock-recipe", recipe = "empty-dt-fuel" },
      { type = "unlock-recipe", recipe = "dt-fuel" },
    },
  },
  {
    type = "technology",
    name = "kr-matter-tech-card",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/technologies/matter-tech-card.png",
    icon_size = 256,
    unit = {
      time = 60,
      count = 750,
      ingredients = {
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
      },
    },
    prerequisites = { "kr-fusion-energy" },
    effects = {
      { type = "unlock-recipe", recipe = "matter-research-data" },
      { type = "unlock-recipe", recipe = "matter-tech-card" },
    },
  },
  {
    type = "technology",
    name = "kr-military-5",
    localised_description = { "technology-description.military" },
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/technologies/military-5.png",
    icon_size = 256,
    order = "g-d-d",
    unit = {
      time = 45,
      count = 500,
      ingredients = {
        { "automation-science-pack", 1 },
        { "logistic-science-pack", 1 },
        { "military-science-pack", 1 },
        { "chemical-science-pack", 1 },
        { "utility-science-pack", 1 },
      },
    },
    prerequisites = {
      "military-4",
      "kr-lithium-sulfur-battery",
      "kr-quarry-minerals-extraction",
    },
    effects = {
      { type = "unlock-recipe", recipe = "impulse-rifle" },
      { type = "unlock-recipe", recipe = "impulse-rifle-ammo" },
      { type = "unlock-recipe", recipe = "imersite-rounds-magazine" },
      { type = "unlock-recipe", recipe = "heavy-rocket-launcher" },
      { type = "unlock-recipe", recipe = "heavy-rocket" },
    },
  },
  {
    type = "technology",
    name = "kr-quantum-computer",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/technologies/quantum-computer.png",
    icon_size = 256,
    unit = {
      time = 60,
      count = 750,
      ingredients = {
        { "automation-science-pack", 1 },
        { "logistic-science-pack", 1 },
        { "chemical-science-pack", 1 },
        { "production-science-pack", 1 },
        { "utility-science-pack", 1 },
      },
    },
    prerequisites = { "kr-ai-core" },
    effects = {
      { type = "unlock-recipe", recipe = "kr-quantum-computer" },
    },
  },
})
