-- settings for Exotic Industries
ei_lib = require("lib/lib")
-- Tesla's Legacy now rides EI's main settings stage instead of owning a separate entry point.
-- Requiring the vendored settings here keeps the public setting list in one place and avoids
-- making the embedded TL module look like an independent top-level mod again.
require("teslas_legacy.settings")
-- These bounds feed EI's entity-update tuning setting later in this file. The minimum stays
-- above zero so every updater family still runs, while the maximum remains a "safe large"
-- value that divides cleanly for EI's staggered update buckets.
local localMinimumFullUpdateTicks =  9 --default is 60
local localMaximumFullUpdateTicks =  6003 --divides evenly
data:extend({
  {
      name = "ei-tech-scaling-maxCost",
      type = "string-setting",
      setting_type = "startup",
      default_value = "Default",
      allowed_values = {"Sunday stroll", "Walk in the park", "Almost free","Very Cheap","Default", "More Cheap", "Cheap",  "Fairly priced","Less Expensive","Expensive", "Very Expensive"},
      order  = "a1",
  },
  {
      name = "ei-tech-scaling-startPrice",
      type = "int-setting",
      setting_type = "startup",
      default_value = 10,
      minimum_value = 1,
      maximum_value = 10000,
      order  = "a2",
  },
  {
      name = "ei-tech-scaling-additionalMultiplier",
      type = "int-setting",
      setting_type = "startup",
      default_value = 1,
      minimum_value = 1,
      maximum_value = 100,
      order  = "a2-1",
  },
  {
      name = "ei-tech-scaling-curveForm",
      type = "string-setting",
      setting_type = "startup",
      default_value = "age-ramp",
      allowed_values = {"linear", "quadratic", "exponential", "age-ramp"},
      order  = "a3",
  },
  {
      name = "ei-science-pack-yield-dark",
      type = "int-setting",
      setting_type = "startup",
      default_value = 2,
      minimum_value = 1,
      maximum_value = 10,
      order  = "a4a",
  },
  {
      name = "ei-science-pack-yield-steam",
      type = "int-setting",
      setting_type = "startup",
      default_value = 2,
      minimum_value = 1,
      maximum_value = 10,
      order  = "a4b",
  },
    {
      name = "ei-science-pack-yield-electricity",
      type = "int-setting",
      setting_type = "startup",
      default_value = 2,
      minimum_value = 1,
      maximum_value = 10,
      order  = "a4c",
  },
    {
      name = "ei-science-pack-yield-computer",
      type = "int-setting",
      setting_type = "startup",
      default_value = 2,
      minimum_value = 1,
      maximum_value = 10,
      order  = "a4d",
  },
    {
      name = "ei-science-pack-yield-simulation",
      type = "int-setting",
      setting_type = "startup",
      default_value = 2,
      minimum_value = 1,
      maximum_value = 10,
      order  = "a4e",
  },
    {
      name = "ei-science-pack-yield-alien",
      type = "int-setting",
      setting_type = "startup",
      default_value = 2,
      minimum_value = 1,
      maximum_value = 10,
      order  = "a4f",
  },
    {
      name = "ei-science-pack-yield-quantum",
      type = "int-setting",
      setting_type = "startup",
      default_value = 1,
      minimum_value = 1,
      maximum_value = 10,
      order  = "a4g",
  },
    {
      name = "ei-science-pack-yield-fusion-quantum",
      type = "int-setting",
      setting_type = "startup",
      default_value = 1,
      minimum_value = 1,
      maximum_value = 10,
      order  = "a4h",
  },
    {
      name = "ei-science-pack-yield-exotic",
      type = "int-setting",
      setting_type = "startup",
      default_value = 1,
      minimum_value = 1,
      maximum_value = 10,
      order  = "a4i",
  },
    {
      name = "ei-science-pack-yield-black-hole",
      type = "int-setting",
      setting_type = "startup",
      default_value = 1,
      minimum_value = 1,
      maximum_value = 10,
      order  = "a4j",
  },
  {
      name = "ei-pipe-to-ground-length",
      type = "int-setting",
      setting_type = "startup",
      default_value = 20,
      minimum_value = 10,
      maximum_value = 20,
      order  = "a5",
  },
  {
      name = "ei-nuclear-reactor-energy-output",
      type = "string-setting",
      setting_type = "startup",
      default_value = "200MW",
      allowed_values = {"150MW", "175MW", "200MW", "225MW", "250MW"},
      order  = "a6",
  },
  {
      name = "ei-rocket-launch-pollution-mode",
      type = "string-setting",
      setting_type = "startup",
      default_value = "linear",
      allowed_values = {"linear", "quadratic", "exponential", "threshold", "hybrid"},
      order  = "a7",
  },
  {
      name = "ei-rocket-launch-pollution-cap",
      type = "int-setting",
      setting_type = "startup",
      default_value = 10000,
      minimum_value = 5000,
      maximum_value = 100000,
      order  = "a7b",
  },
  {
      name = "ei-flammable-rupture-fidelity",
      type = "string-setting",
      setting_type = "startup",
      default_value = "standard",
      allowed_values = {"lean", "standard", "cinematic", "unbounded"},
      order  = "a7ba",
  },
  {
      name = "ei-fulgora-day-length-variation-max-multiplier",
      type = "double-setting",
      setting_type = "startup",
      default_value = 2,
      minimum_value = 1.5,
      maximum_value = 3,
      order  = "a7c",
  },
  {
      name = "ei-fulgora-day-length-variation-min-multiplier",
      type = "double-setting",
      setting_type = "startup",
      default_value = 0.1,
      minimum_value = 0.1,
      maximum_value = 0.5,
      order  = "a7d",
  },
  {
      name = "ei-nuclear-reactor-remove-bonus",
      type = "bool-setting",
      setting_type = "startup",
      default_value = true,
      order  = "a7",
      hidden = true, --Disabling it concurrently with the EI nuclear reactor buffs is dishonorable.
  },
  {
      name = "ei-barrel-capacity",
      type = "int-setting",
      setting_type = "startup",
      default_value = 1000,
      minimum_value = 50,
      maximum_value = 2000,
      order  = "a8",
  },
  {
      name = "ei-beacon-overload",
      type = "bool-setting",
      setting_type = "startup",
      default_value = true,
      order  = "b1",
      hidden = true, --Disabling it concurrently with the EI beacon buffs is dishonorable.
  },
  {
      name = "ei-em_train_glow",
      type = "bool-setting",
      setting_type = "startup",
      default_value = true,
      order  = "b1b",
  },
  {
      name = "ei-em_train_glow_timetolive",
      type = "int-setting",
      setting_type = "startup",
      default_value = 60,
      minimum_value = 1,
      maximum_value = 600,
      order  = "b1bb",
  },
  {
      name = "ei-em_charger_glow",
      type = "bool-setting",
      setting_type = "startup",
      default_value = true,
      order  = "b1c",
  },
  {
      name = "ei-em_charger_glow_timetolive",
      type = "int-setting",
      setting_type = "startup",
      default_value = 60,
      minimum_value = 1,
      maximum_value = 600,
      order  = "b1d",
  },
  {
      name = "ei-em_updater_que",
      type = "string-setting",
      setting_type = "startup",
      default_value = "Beam",
      allowed_values = {"Off", "Beam", "Ring"},
      order  = "b2",
  },
  {
      name = "ei-em_updater_que_width",
      type = "int-setting",
      setting_type = "startup",
      default_value = 3,
      minimum_value = 1,
      maximum_value = 32,
      order  = "b3",
  },
  {
      name = "ei-em_updater_que_transparency",
      type = "int-setting",
      setting_type = "startup",
      default_value = 88,
      minimum_value = 1,
      maximum_value = 100,
      order  = "b3b",
  },
  {
      name = "ei-em_updater_que_timetolive",
      type = "int-setting",
      setting_type = "startup",
      default_value = 20,
      minimum_value = 1,
      maximum_value = 600,
      order  = "b3c",
  },
  {
      name = "ei-max_updates_per_tick",
      type = "int-setting",
      setting_type = "startup",
      default_value = 10,
      minimum_value = 1,
      maximum_value = 100,
      order  = "b5",
  },
  {
      name = "ei-ticks_per_full_update",
      type = "int-setting",
      setting_type = "startup",
      default_value = 60,
      minimum_value = localMinimumFullUpdateTicks,
      maximum_value = localMaximumFullUpdateTicks,
      order  = "b6",
  },
  {
      name = "ei-expanded-gui",
      type = "bool-setting",
      setting_type = "startup",
      default_value = false,
      order  = "c1a",
  },
  {
      name = "ei-tech-tree-flatten",
      type = "bool-setting",
      setting_type = "startup",
      default_value = false,
      order  = "c1d",
  },
  {
      name = "ei-no-triggers",
      type = "bool-setting",
      setting_type = "startup",
      default_value = true,
      order  = "c1e",
  },
  {
      name = "ei-no-tech-scaling",
      type = "bool-setting",
      setting_type = "startup",
      default_value = false,
      order  = "c1f",
      hidden = true, --Commit to the vision of the mod, don't disable this.
  },
  {
      name = "ei-solar-icon-scaling",
      type = "string-setting",
      setting_type = "startup",
      default_value = "75% (Vanilla)",
      allowed_values = {
      "25%",
      "50%",
      "75% (Vanilla)",
      "100%",
      "125%",
      "150%",
      "175%",
      "200%",
      "225%",
      "250%",
      "275%",
      "300%"
    },
      order  = "c1f1",
  },
    {
        name = "ei-fueler_range",
        type = "int-setting",
        setting_type = "startup",
        default_value = 16,
        minimum_value = 1,
        maximum_value = 32,
        order  = "c1f2",
    },
  {
      name = "ei-menu-background",
      type = "string-setting",
      setting_type = "startup",
      default_value = "The Crystal That Screams",
      allowed_values = {
      "The Crystal That Screams",
      "Vector Bifurcation: Portal Ignition",
      "Saluting the Solar Core",
      "Daemonic Invitation",
      "Yin and Yang: Cloudflesh",
      "Industrial Dominance: Crystalline Vigil",
      "Choking Smog: Ascension Protocol"},
      order  = "c1g1",
  },
  {
      name = "ei-nauvis-main-tracks-override",
      type = "bool-setting",
      setting_type = "startup",
      default_value = true,
      order  = "c1g2",
  },
  {
      name = "ei-nauvis-interlude-tracks-override",
      type = "bool-setting",
      setting_type = "startup",
      default_value = true,
      order  = "c1g3",
  },
  {
      name = "ei-check-for-recipe-icons-improvement-mod",
      type = "bool-setting",
      setting_type = "startup",
      default_value = true,
      order  = "c1g4",
  },
  {
      name = "ei-nauvis-pressure-grace",
      type = "bool-setting",
      setting_type = "startup",
      default_value = true,
      order  = "c1g5",
  },
  {
      name = "ei-enemy-difficulty",
      type = "string-setting",
      setting_type = "startup",
      default_value = "Tempered",
      allowed_values = {"Merciful", "Gentle", "Tempered", "Original", "Severe", "Nightmare", "Impossible"},
      order  = "c1g5a",
  },
  {
      name = "ei-gate-difficulty",
      type = "string-setting",
      setting_type = "startup",
      default_value = "Recovered",
      allowed_values = {"Recovered", "Attuned", "Resonant", "Paradox"},
      order  = "c1g5b",
  },
  {
      name = "ei-enable-preliminary-k2so-patch",
      type = "bool-setting",
      setting_type = "startup",
      default_value = false,
      order  = "zzzz-k2so",
  },
  {
      name = "ei-gate-notifications",
      type = "bool-setting",
      setting_type = "runtime-per-user",
      default_value = true,
      order  = "e1",
  },
  {
      name = "ei-black-hole-notifications",
      type = "bool-setting",
      setting_type = "runtime-per-user",
      default_value = true,
      order  = "e2",
  },
  {
      name = "ei-matter-machine-notifications",
      type = "bool-setting",
      setting_type = "runtime-per-user",
      default_value = true,
      order  = "e3",
  },
  {
      name = "ei-insulated-pipe-notifications",
      type = "bool-setting",
      setting_type = "runtime-per-user",
      default_value = true,
      order  = "e4",
  },
  --this was used before the cyclic per tick entity updater was made
    {
        name = "ei_fueler_max_updates_per_tick",
        type = "int-setting",
        setting_type = "startup",
        setting_type = "startup",
        default_value = 1,
        minimum_value = 1,
        maximum_value = 100,
        order  = "d1",
        hidden = true
    },
})
