-- Generated by derive-accent-layers.py from body.lua
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 8,
  ["height"] = 457,
  ["line_length"] = 4,
  ["lines_per_file"] = 8,
  ["scale"] = 0.5,
  ["shift"] = {0 / 64, -64.5 / 64},
  ["sprite_count"] = 256,
  ["width"] = 484,
  ["derived_role"] = "mask",
  ["source_layer"] = "body",
  ["source_sha256"] = "1098a97325004dd33b69430b006e5733c311e215c3fd7aab756ff1e01acd0237",
}
