-- Generated by derive-accent-layers.py from sloped.lua
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 8,
  ["height"] = 550,
  ["line_length"] = 4,
  ["lines_per_file"] = 5,
  ["scale"] = 0.5,
  ["shift"] = {0 / 64, -26 / 64},
  ["sprite_count"] = 160,
  ["width"] = 526,
  ["derived_role"] = "glow",
  ["source_layer"] = "sloped",
  ["source_sha256"] = "21a126905d478403b01da290ddb79fc2877f9ed57da08d206acbda0bb7fc5b4d",
}
