--==============================================================================
-- ESIR FILE MAP
-- owns: generated Emerald Apocalypse hover tank 64-direction hover foot offsets
-- loaded_by: scripts/control/emerald-apocalypse-hover-tank.lua via lib require
-- cadence: runtime module load
-- forwarded_events: none
-- storage_roots: none
-- gui_ids: none
-- remote_interfaces: none
-- rebuild_on: approved hover tank render framing or hover foot component picks change
--==============================================================================

-- Generated by generate_hover_emitter_offsets.py from the approved final render manifest.
-- Do not hand-edit values; regenerate after changing the hover tank render framing or foot picks.
local HOVER_EMITTER_OFFSETS_BY_DIRECTION = {
    {
        {x = 0.9920, y = 5.3938, radius_scale = 1.00},
        {x = -0.8281, y = 5.4598, radius_scale = 1.00},
        {x = 2.3820, y = 1.4758, radius_scale = 0.92},
        {x = -2.5249, y = 1.7441, radius_scale = 0.92},
    },
    {
        {x = 0.6101, y = 5.4494, radius_scale = 1.00},
        {x = -1.2095, y = 5.3890, radius_scale = 1.00},
        {x = 2.5258, y = 1.6463, radius_scale = 0.92},
        {x = -2.3801, y = 1.5737, radius_scale = 0.92},
    },
    {
        {x = 0.2224, y = 5.4783, radius_scale = 1.00},
        {x = -1.5792, y = 5.2922, radius_scale = 1.00},
        {x = 2.6452, y = 1.8259, radius_scale = 0.92},
        {x = -2.2123, y = 1.4142, radius_scale = 0.92},
    },
    {
        {x = -0.1675, y = 5.4802, radius_scale = 1.00},
        {x = -1.9337, y = 5.1701, radius_scale = 1.00},
        {x = 2.7392, y = 2.0130, radius_scale = 0.92},
        {x = -2.0233, y = 1.2670, radius_scale = 0.92},
    },
    {
        {x = -0.5558, y = 5.4551, radius_scale = 1.00},
        {x = -2.2696, y = 5.0241, radius_scale = 1.00},
        {x = 2.8068, y = 2.2056, radius_scale = 0.92},
        {x = -1.8148, y = 1.1337, radius_scale = 0.92},
    },
    {
        {x = -0.9387, y = 5.4032, radius_scale = 1.00},
        {x = -2.5836, y = 4.8555, radius_scale = 1.00},
        {x = 2.8473, y = 2.4020, radius_scale = 0.92},
        {x = -1.5888, y = 1.0155, radius_scale = 0.92},
    },
    {
        {x = -1.3126, y = 5.3250, radius_scale = 1.00},
        {x = -2.8728, y = 4.6660, radius_scale = 1.00},
        {x = 2.8605, y = 2.6003, radius_scale = 0.92},
        {x = -1.3475, y = 0.9135, radius_scale = 0.92},
    },
    {
        {x = -1.6739, y = 5.2212, radius_scale = 1.00},
        {x = -3.1343, y = 4.4573, radius_scale = 1.00},
        {x = 2.8460, y = 2.7986, radius_scale = 0.92},
        {x = -1.0932, y = 0.8287, radius_scale = 0.92},
    },
    {
        {x = -2.0190, y = 5.0930, radius_scale = 1.00},
        {x = -3.3656, y = 4.2315, radius_scale = 1.00},
        {x = 2.8042, y = 2.9948, radius_scale = 0.92},
        {x = -0.8284, y = 0.7619, radius_scale = 0.92},
    },
    {
        {x = -2.3447, y = 4.9414, radius_scale = 1.00},
        {x = -3.5644, y = 3.9908, radius_scale = 1.00},
        {x = 2.7354, y = 3.1873, radius_scale = 0.92},
        {x = -0.5556, y = 0.7139, radius_scale = 0.92},
    },
    {
        {x = -2.6478, y = 4.7680, radius_scale = 1.00},
        {x = -3.7290, y = 3.7374, radius_scale = 1.00},
        {x = 2.6402, y = 3.3740, radius_scale = 0.92},
        {x = -0.2775, y = 0.6849, radius_scale = 0.92},
    },
    {
        {x = -2.9254, y = 4.5744, radius_scale = 1.00},
        {x = -3.8577, y = 3.4739, radius_scale = 1.00},
        {x = 2.5196, y = 3.5532, radius_scale = 0.92},
        {x = 0.0033, y = 0.6754, radius_scale = 0.92},
    },
    {
        {x = -3.1748, y = 4.3624, radius_scale = 1.00},
        {x = -3.9491, y = 3.2027, radius_scale = 1.00},
        {x = 2.3748, y = 3.7233, radius_scale = 0.92},
        {x = 0.2841, y = 0.6854, radius_scale = 0.92},
    },
    {
        {x = -3.3936, y = 4.1343, radius_scale = 1.00},
        {x = -4.0026, y = 2.9265, radius_scale = 1.00},
        {x = 2.2070, y = 3.8824, radius_scale = 0.92},
        {x = 0.5621, y = 0.7148, radius_scale = 0.92},
    },
    {
        {x = -3.5798, y = 3.8920, radius_scale = 1.00},
        {x = -4.0175, y = 2.6479, radius_scale = 1.00},
        {x = 2.0180, y = 4.0292, radius_scale = 0.92},
        {x = 0.8348, y = 0.7633, radius_scale = 0.92},
    },
    {
        {x = -3.7315, y = 3.6380, radius_scale = 1.00},
        {x = -3.9938, y = 2.3696, radius_scale = 1.00},
        {x = 1.8096, y = 4.1622, radius_scale = 0.92},
        {x = 1.0993, y = 0.8305, radius_scale = 0.92},
    },
    {
        {x = -3.8473, y = 3.3748, radius_scale = 1.00},
        {x = -3.9315, y = 2.0943, radius_scale = 1.00},
        {x = 1.5838, y = 4.2800, radius_scale = 0.92},
        {x = 1.3533, y = 0.9157, radius_scale = 0.92},
    },
    {
        {x = -3.9260, y = 3.1047, radius_scale = 1.00},
        {x = -3.8314, y = 1.8246, radius_scale = 1.00},
        {x = 1.3427, y = 4.3817, radius_scale = 0.92},
        {x = 1.5943, y = 1.0181, radius_scale = 0.92},
    },
    {
        {x = -3.9669, y = 2.8306, radius_scale = 1.00},
        {x = -3.6944, y = 1.5632, radius_scale = 1.00},
        {x = 1.0886, y = 4.4662, radius_scale = 0.92},
        {x = 1.8199, y = 1.1367, radius_scale = 0.92},
    },
    {
        {x = -3.9696, y = 2.5549, radius_scale = 1.00},
        {x = -3.5218, y = 1.3125, radius_scale = 1.00},
        {x = 0.8241, y = 4.5326, radius_scale = 0.92},
        {x = 2.0280, y = 1.2704, radius_scale = 0.92},
    },
    {
        {x = -3.9340, y = 2.2803, radius_scale = 1.00},
        {x = -3.3154, y = 1.0750, radius_scale = 1.00},
        {x = 0.5517, y = 4.5804, radius_scale = 0.92},
        {x = 2.2166, y = 1.4178, radius_scale = 0.92},
    },
    {
        {x = -3.8606, y = 2.0095, radius_scale = 1.00},
        {x = -3.0769, y = 0.8529, radius_scale = 1.00},
        {x = 0.2739, y = 4.6091, radius_scale = 0.92},
        {x = 2.3838, y = 1.5776, radius_scale = 0.92},
    },
    {
        {x = -3.7500, y = 1.7452, radius_scale = 1.00},
        {x = -2.8089, y = 0.6485, radius_scale = 1.00},
        {x = -0.0065, y = 4.6184, radius_scale = 0.92},
        {x = 2.5280, y = 1.7482, radius_scale = 0.92},
    },
    {
        {x = -3.6033, y = 1.4897, radius_scale = 1.00},
        {x = -2.5138, y = 0.4636, radius_scale = 1.00},
        {x = -0.2868, y = 4.6082, radius_scale = 0.92},
        {x = 2.6479, y = 1.9280, radius_scale = 0.92},
    },
    {
        {x = -3.4219, y = 1.2457, radius_scale = 1.00},
        {x = -2.1945, y = 0.3000, radius_scale = 1.00},
        {x = -0.5644, y = 4.5786, radius_scale = 0.92},
        {x = 2.7423, y = 2.1153, radius_scale = 0.92},
    },
    {
        {x = -3.2075, y = 1.0154, radius_scale = 1.00},
        {x = -1.8540, y = 0.1594, radius_scale = 1.00},
        {x = -0.8366, y = 4.5299, radius_scale = 0.92},
        {x = 2.8103, y = 2.3082, radius_scale = 0.92},
    },
    {
        {x = -2.9623, y = 0.8011, radius_scale = 1.00},
        {x = -1.4957, y = 0.0430, radius_scale = 1.00},
        {x = -1.1007, y = 4.4626, radius_scale = 0.92},
        {x = 2.8512, y = 2.5048, radius_scale = 0.92},
    },
    {
        {x = -2.6885, y = 0.6048, radius_scale = 1.00},
        {x = -1.1230, y = -0.0480, radius_scale = 1.00},
        {x = -1.3541, y = 4.3774, radius_scale = 0.92},
        {x = 2.8647, y = 2.7034, radius_scale = 0.92},
    },
    {
        {x = -2.3888, y = 0.4284, radius_scale = 1.00},
        {x = -0.7395, y = -0.1127, radius_scale = 1.00},
        {x = -1.5946, y = 4.2749, radius_scale = 0.92},
        {x = 2.8506, y = 2.9019, radius_scale = 0.92},
    },
    {
        {x = -2.0661, y = 0.2736, radius_scale = 1.00},
        {x = -0.3488, y = -0.1505, radius_scale = 1.00},
        {x = -1.8197, y = 4.1563, radius_scale = 0.92},
        {x = 2.8090, y = 3.0985, radius_scale = 0.92},
    },
    {
        {x = -1.7235, y = 0.1420, radius_scale = 1.00},
        {x = 0.0452, y = -0.1610, radius_scale = 1.00},
        {x = -2.0272, y = 4.0227, radius_scale = 0.92},
        {x = 2.7404, y = 3.2913, radius_scale = 0.92},
    },
    {
        {x = -1.3643, y = 0.0347, radius_scale = 1.00},
        {x = 0.4388, y = -0.1442, radius_scale = 1.00},
        {x = -2.2153, y = 3.8753, radius_scale = 0.92},
        {x = 2.6454, y = 3.4784, radius_scale = 0.92},
    },
    {
        {x = -0.9920, y = -0.0471, radius_scale = 1.00},
        {x = 0.8281, y = -0.1002, radius_scale = 1.00},
        {x = -2.3820, y = 3.7156, radius_scale = 0.92},
        {x = 2.5249, y = 3.6580, radius_scale = 0.92},
    },
    {
        {x = -0.6101, y = -0.1028, radius_scale = 1.00},
        {x = 1.2095, y = -0.0294, radius_scale = 1.00},
        {x = -2.5258, y = 3.5451, radius_scale = 0.92},
        {x = 2.3801, y = 3.8284, radius_scale = 0.92},
    },
    {
        {x = -0.2224, y = -0.1317, radius_scale = 1.00},
        {x = 1.5792, y = 0.0675, radius_scale = 1.00},
        {x = -2.6452, y = 3.3655, radius_scale = 0.92},
        {x = 2.2123, y = 3.9879, radius_scale = 0.92},
    },
    {
        {x = 0.1675, y = -0.1336, radius_scale = 1.00},
        {x = 1.9337, y = 0.1895, radius_scale = 1.00},
        {x = -2.7392, y = 3.1785, radius_scale = 0.92},
        {x = 2.0233, y = 4.1351, radius_scale = 0.92},
    },
    {
        {x = 0.5558, y = -0.1085, radius_scale = 1.00},
        {x = 2.2696, y = 0.3355, radius_scale = 1.00},
        {x = -2.8068, y = 2.9858, radius_scale = 0.92},
        {x = 1.8148, y = 4.2684, radius_scale = 0.92},
    },
    {
        {x = 0.9387, y = -0.0566, radius_scale = 1.00},
        {x = 2.5836, y = 0.5041, radius_scale = 1.00},
        {x = -2.8473, y = 2.7894, radius_scale = 0.92},
        {x = 1.5888, y = 4.3866, radius_scale = 0.92},
    },
    {
        {x = 1.3126, y = 0.0216, radius_scale = 1.00},
        {x = 2.8728, y = 0.6936, radius_scale = 1.00},
        {x = -2.8605, y = 2.5911, radius_scale = 0.92},
        {x = 1.3475, y = 4.4886, radius_scale = 0.92},
    },
    {
        {x = 1.6739, y = 0.1254, radius_scale = 1.00},
        {x = 3.1343, y = 0.9023, radius_scale = 1.00},
        {x = -2.8460, y = 2.3929, radius_scale = 0.92},
        {x = 1.0932, y = 4.5734, radius_scale = 0.92},
    },
    {
        {x = 2.0190, y = 0.2537, radius_scale = 1.00},
        {x = 3.3656, y = 1.1281, radius_scale = 1.00},
        {x = -2.8042, y = 2.1966, radius_scale = 0.92},
        {x = 0.8284, y = 4.6402, radius_scale = 0.92},
    },
    {
        {x = 2.3447, y = 0.4053, radius_scale = 1.00},
        {x = 3.5644, y = 1.3688, radius_scale = 1.00},
        {x = -2.7354, y = 2.0042, radius_scale = 0.92},
        {x = 0.5556, y = 4.6882, radius_scale = 0.92},
    },
    {
        {x = 2.6478, y = 0.5787, radius_scale = 1.00},
        {x = 3.7290, y = 1.6222, radius_scale = 1.00},
        {x = -2.6402, y = 1.8174, radius_scale = 0.92},
        {x = 0.2775, y = 4.7172, radius_scale = 0.92},
    },
    {
        {x = 2.9254, y = 0.7723, radius_scale = 1.00},
        {x = 3.8577, y = 1.8857, radius_scale = 1.00},
        {x = -2.5196, y = 1.6382, radius_scale = 0.92},
        {x = -0.0033, y = 4.7267, radius_scale = 0.92},
    },
    {
        {x = 3.1748, y = 0.9842, radius_scale = 1.00},
        {x = 3.9491, y = 2.1569, radius_scale = 1.00},
        {x = -2.3748, y = 1.4682, radius_scale = 0.92},
        {x = -0.2841, y = 4.7167, radius_scale = 0.92},
    },
    {
        {x = 3.3936, y = 1.2124, radius_scale = 1.00},
        {x = 4.0026, y = 2.4332, radius_scale = 1.00},
        {x = -2.2070, y = 1.3090, radius_scale = 0.92},
        {x = -0.5621, y = 4.6873, radius_scale = 0.92},
    },
    {
        {x = 3.5798, y = 1.4546, radius_scale = 1.00},
        {x = 4.0175, y = 2.7118, radius_scale = 1.00},
        {x = -2.0180, y = 1.1622, radius_scale = 0.92},
        {x = -0.8348, y = 4.6388, radius_scale = 0.92},
    },
    {
        {x = 3.7315, y = 1.7086, radius_scale = 1.00},
        {x = 3.9938, y = 2.9901, radius_scale = 1.00},
        {x = -1.8096, y = 1.0293, radius_scale = 0.92},
        {x = -1.0993, y = 4.5716, radius_scale = 0.92},
    },
    {
        {x = 3.8473, y = 1.9719, radius_scale = 1.00},
        {x = 3.9315, y = 3.2654, radius_scale = 1.00},
        {x = -1.5838, y = 0.9114, radius_scale = 0.92},
        {x = -1.3533, y = 4.4864, radius_scale = 0.92},
    },
    {
        {x = 3.9260, y = 2.2419, radius_scale = 1.00},
        {x = 3.8314, y = 3.5350, radius_scale = 1.00},
        {x = -1.3427, y = 0.8097, radius_scale = 0.92},
        {x = -1.5943, y = 4.3840, radius_scale = 0.92},
    },
    {
        {x = 3.9669, y = 2.5161, radius_scale = 1.00},
        {x = 3.6944, y = 3.7965, radius_scale = 1.00},
        {x = -1.0886, y = 0.7253, radius_scale = 0.92},
        {x = -1.8199, y = 4.2654, radius_scale = 0.92},
    },
    {
        {x = 3.9696, y = 2.7918, radius_scale = 1.00},
        {x = 3.5218, y = 4.0471, radius_scale = 1.00},
        {x = -0.8241, y = 0.6588, radius_scale = 0.92},
        {x = -2.0280, y = 4.1317, radius_scale = 0.92},
    },
    {
        {x = 3.9340, y = 3.0663, radius_scale = 1.00},
        {x = 3.3154, y = 4.2847, radius_scale = 1.00},
        {x = -0.5517, y = 0.6110, radius_scale = 0.92},
        {x = -2.2166, y = 3.9843, radius_scale = 0.92},
    },
    {
        {x = 3.8606, y = 3.3371, radius_scale = 1.00},
        {x = 3.0769, y = 4.5067, radius_scale = 1.00},
        {x = -0.2739, y = 0.5824, radius_scale = 0.92},
        {x = -2.3838, y = 3.8245, radius_scale = 0.92},
    },
    {
        {x = 3.7500, y = 3.6015, radius_scale = 1.00},
        {x = 2.8089, y = 4.7112, radius_scale = 1.00},
        {x = 0.0065, y = 0.5731, radius_scale = 0.92},
        {x = -2.5280, y = 3.6539, radius_scale = 0.92},
    },
    {
        {x = 3.6033, y = 3.8569, radius_scale = 1.00},
        {x = 2.5138, y = 4.8961, radius_scale = 1.00},
        {x = 0.2868, y = 0.5833, radius_scale = 0.92},
        {x = -2.6479, y = 3.4741, radius_scale = 0.92},
    },
    {
        {x = 3.4219, y = 4.1010, radius_scale = 1.00},
        {x = 2.1945, y = 5.0596, radius_scale = 1.00},
        {x = 0.5644, y = 0.6128, radius_scale = 0.92},
        {x = -2.7423, y = 3.2868, radius_scale = 0.92},
    },
    {
        {x = 3.2075, y = 4.3312, radius_scale = 1.00},
        {x = 1.8540, y = 5.2003, radius_scale = 1.00},
        {x = 0.8366, y = 0.6615, radius_scale = 0.92},
        {x = -2.8103, y = 3.0939, radius_scale = 0.92},
    },
    {
        {x = 2.9623, y = 4.5456, radius_scale = 1.00},
        {x = 1.4957, y = 5.3166, radius_scale = 1.00},
        {x = 1.1007, y = 0.7288, radius_scale = 0.92},
        {x = -2.8512, y = 2.8973, radius_scale = 0.92},
    },
    {
        {x = 2.6885, y = 4.7419, radius_scale = 1.00},
        {x = 1.1230, y = 5.4076, radius_scale = 1.00},
        {x = 1.3541, y = 0.8141, radius_scale = 0.92},
        {x = -2.8647, y = 2.6987, radius_scale = 0.92},
    },
    {
        {x = 2.3888, y = 4.9182, radius_scale = 1.00},
        {x = 0.7395, y = 5.4723, radius_scale = 1.00},
        {x = 1.5946, y = 0.9165, radius_scale = 0.92},
        {x = -2.8506, y = 2.5002, radius_scale = 0.92},
    },
    {
        {x = 2.0661, y = 5.0730, radius_scale = 1.00},
        {x = 0.3488, y = 5.5101, radius_scale = 1.00},
        {x = 1.8197, y = 1.0351, radius_scale = 0.92},
        {x = -2.8090, y = 2.3036, radius_scale = 0.92},
    },
    {
        {x = 1.7235, y = 5.2046, radius_scale = 1.00},
        {x = -0.0452, y = 5.5206, radius_scale = 1.00},
        {x = 2.0272, y = 1.1688, radius_scale = 0.92},
        {x = -2.7404, y = 2.1108, radius_scale = 0.92},
    },
    {
        {x = 1.3643, y = 5.3119, radius_scale = 1.00},
        {x = -0.4388, y = 5.5038, radius_scale = 1.00},
        {x = 2.2153, y = 1.3161, radius_scale = 0.92},
        {x = -2.6454, y = 1.9237, radius_scale = 0.92},
    },
}

return HOVER_EMITTER_OFFSETS_BY_DIRECTION
