#!/usr/bin/env python3
"""Derive narrow Spritter-matched accent mask/glow layers for ESIR trains."""

from __future__ import annotations

import argparse
import hashlib
import re
from dataclasses import dataclass
from pathlib import Path

import numpy as np
from PIL import Image, ImageChops, ImageDraw, ImageFilter


TARGETS = {
    "nuclear-locomotive": "exotic-space-industries-remembrance-graphics-4/graphics/entities/nuclear-locomotive",
    "advanced-cargo-wagon": "exotic-space-industries-remembrance-graphics-4/graphics/entities/advanced-cargo-wagon",
    "advanced-fluid-wagon": "exotic-space-industries-remembrance-graphics-4/graphics/entities/advanced-fluid-wagon",
}

LAYER_SPECS = {
    "nuclear-locomotive": {
        "body": ("glow",),
        "sloped": ("glow",),
    },
    "advanced-cargo-wagon": {
        "body": ("mask", "glow"),
        "sloped": ("mask", "glow"),
    },
    "advanced-fluid-wagon": {
        "body": ("mask", "glow"),
        "sloped": ("mask", "glow"),
    },
}

@dataclass(frozen=True)
class Metadata:
    file_count: int
    height: int
    line_length: int
    lines_per_file: int
    sprite_count: int
    width: int


def parse_metadata(path: Path) -> Metadata:
    text = path.read_text(encoding="utf-8")
    values: dict[str, int] = {}
    for key in ("file_count", "height", "line_length", "lines_per_file", "sprite_count", "width"):
        match = re.search(rf'\["{key}"\]\s*=\s*(\d+)', text)
        if not match:
            raise ValueError(f"{path} is missing metadata key {key}")
        values[key] = int(match.group(1))
    return Metadata(**values)


def source_hash(target_dir: Path, layer: str, metadata: Metadata) -> str:
    digest = hashlib.sha256()
    digest.update((target_dir / f"{layer}.lua").read_bytes())
    for index in range(metadata.file_count):
        digest.update((target_dir / f"{layer}-{index}.png").read_bytes())
    return digest.hexdigest()


def write_metadata(source_path: Path, target_path: Path, source_layer: str, role: str, digest: str) -> None:
    text = source_path.read_text(encoding="utf-8")
    text = re.sub(
        r"^-- Generated by spritter .*$",
        f"-- Generated by derive-accent-layers.py from {source_layer}.lua",
        text,
        count=1,
        flags=re.MULTILINE,
    )
    provenance = (
        f'  ["derived_role"] = "{role}",\n'
        f'  ["source_layer"] = "{source_layer}",\n'
        f'  ["source_sha256"] = "{digest}",\n'
    )
    text = re.sub(r"}\s*$", provenance + "}\n", text)
    target_path.write_text(text, encoding="utf-8", newline="\n")


def saturation(r: int, g: int, b: int) -> float:
    maximum = max(r, g, b)
    minimum = min(r, g, b)
    if maximum <= 0:
        return 0.0
    return (maximum - minimum) / maximum


def luma(r: int, g: int, b: int) -> float:
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def is_cyan_light(r: int, g: int, b: int) -> bool:
    sat = saturation(r, g, b)
    return (
        b >= 82
        and g >= 66
        and sat >= 0.22
        and b > r * 1.18 + 6
        and g > r * 1.06 + 2
        and luma(r, g, b) >= 52
    )


def is_green_light(r: int, g: int, b: int) -> bool:
    sat = saturation(r, g, b)
    return (
        g >= 92
        and sat >= 0.24
        and g > r * 1.18 + 8
        and g > b * 1.03 + 2
        and luma(r, g, b) >= 54
    )


def is_yellow_accent(r: int, g: int, b: int) -> bool:
    sat = saturation(r, g, b)
    return (
        r >= 108
        and g >= 88
        and b <= 118
        and sat >= 0.26
        and r > b * 1.28 + 10
        and g > b * 1.12 + 8
        and abs(r - g) <= 92
        and luma(r, g, b) >= 78
    )


def glow_color(r: int, g: int, b: int, target: str) -> tuple[int, int, int]:
    if is_cyan_light(r, g, b):
        return (80, 210, 255)
    if is_green_light(r, g, b):
        return (92, 230, 118)
    if target in ("advanced-cargo-wagon", "advanced-fluid-wagon") and is_yellow_accent(r, g, b):
        return (255, 214, 92)
    if target == "nuclear-locomotive" and is_yellow_accent(r, g, b):
        return (255, 212, 78)
    return (0, 0, 0)


def derive_mask_cell(cell: Image.Image) -> tuple[Image.Image, int, int]:
    source = cell.convert("RGBA")
    out = Image.new("RGBA", source.size, (0, 0, 0, 0))
    out_pixels = out.load()
    selected = 0
    opaque = 0

    for y in range(source.height):
        for x in range(source.width):
            r, g, b, a = source.getpixel((x, y))
            if a < 8:
                continue
            opaque += 1
            if is_yellow_accent(r, g, b):
                alpha = min(118, max(24, int(a * 0.46)))
                out_pixels[x, y] = (190, 190, 190, alpha)
                selected += 1

    alpha = out.getchannel("A").filter(ImageFilter.MedianFilter(3))
    base_alpha = source.getchannel("A").point(lambda value: 255 if value >= 8 else 0)
    alpha = ImageChops.multiply(alpha, base_alpha)
    out.putalpha(alpha)
    return out, selected, opaque


def derive_glow_cell(cell: Image.Image, target: str) -> tuple[Image.Image, int, int]:
    source = cell.convert("RGBA")
    out = Image.new("RGBA", source.size, (0, 0, 0, 0))
    out_pixels = out.load()
    selected = 0
    opaque = 0

    for y in range(source.height):
        for x in range(source.width):
            r, g, b, a = source.getpixel((x, y))
            if a < 8:
                continue
            opaque += 1
            if is_cyan_light(r, g, b) or is_green_light(r, g, b) or is_yellow_accent(r, g, b):
                cr, cg, cb = glow_color(r, g, b, target)
                if cr == 0 and cg == 0 and cb == 0:
                    continue
                alpha = min(74, max(18, int(a * 0.24)))
                out_pixels[x, y] = (cr, cg, cb, alpha)
                selected += 1

    alpha = out.getchannel("A").filter(ImageFilter.MaxFilter(3)).filter(ImageFilter.GaussianBlur(0.55))
    base_alpha = source.getchannel("A").point(lambda value: 255 if value >= 8 else 0)
    alpha = ImageChops.multiply(alpha, base_alpha)
    color = out.filter(ImageFilter.GaussianBlur(0.25))
    color.putalpha(alpha)
    return color, selected, opaque


def derive_mask_image(source: Image.Image) -> tuple[Image.Image, int, int]:
    arr = np.asarray(source.convert("RGBA"), dtype=np.uint16)
    red = arr[:, :, 0]
    green = arr[:, :, 1]
    blue = arr[:, :, 2]
    alpha = arr[:, :, 3]
    maximum = np.maximum.reduce([red, green, blue])
    minimum = np.minimum.reduce([red, green, blue])
    sat = np.divide(maximum - minimum, maximum, out=np.zeros_like(maximum, dtype=np.float32), where=maximum > 0)
    lum = 0.2126 * red + 0.7152 * green + 0.0722 * blue
    opaque = alpha >= 8
    yellow = (
        opaque
        & (red >= 108)
        & (green >= 88)
        & (blue <= 118)
        & (sat >= 0.26)
        & (red > blue * 1.28 + 10)
        & (green > blue * 1.12 + 8)
        & (np.abs(red.astype(np.int32) - green.astype(np.int32)) <= 92)
        & (lum >= 78)
    )

    out = np.zeros(arr.shape, dtype=np.uint8)
    out[:, :, 0:3] = 190
    mask_alpha = np.zeros(alpha.shape, dtype=np.uint8)
    scaled_alpha = np.clip((alpha.astype(np.float32) * 0.46).astype(np.uint16), 24, 118).astype(np.uint8)
    mask_alpha[yellow] = scaled_alpha[yellow]
    out[:, :, 3] = mask_alpha

    image = Image.fromarray(out)
    filtered_alpha = image.getchannel("A").filter(ImageFilter.MedianFilter(3))
    base_alpha = source.getchannel("A").point(lambda value: 255 if value >= 8 else 0)
    filtered_alpha = ImageChops.multiply(filtered_alpha, base_alpha)
    image.putalpha(filtered_alpha)
    return image, int(np.count_nonzero(yellow)), int(np.count_nonzero(opaque))


def derive_glow_image(source: Image.Image, target: str) -> tuple[Image.Image, int, int]:
    arr = np.asarray(source.convert("RGBA"), dtype=np.uint16)
    red = arr[:, :, 0]
    green = arr[:, :, 1]
    blue = arr[:, :, 2]
    alpha = arr[:, :, 3]
    maximum = np.maximum.reduce([red, green, blue])
    minimum = np.minimum.reduce([red, green, blue])
    sat = np.divide(maximum - minimum, maximum, out=np.zeros_like(maximum, dtype=np.float32), where=maximum > 0)
    lum = 0.2126 * red + 0.7152 * green + 0.0722 * blue
    opaque = alpha >= 8

    cyan = (
        opaque
        & (blue >= 82)
        & (green >= 66)
        & (sat >= 0.22)
        & (blue > red * 1.18 + 6)
        & (green > red * 1.06 + 2)
        & (lum >= 52)
    )
    green_light = (
        opaque
        & (green >= 92)
        & (sat >= 0.24)
        & (green > red * 1.18 + 8)
        & (green > blue * 1.03 + 2)
        & (lum >= 54)
    )
    yellow = (
        opaque
        & (red >= 108)
        & (green >= 88)
        & (blue <= 118)
        & (sat >= 0.26)
        & (red > blue * 1.28 + 10)
        & (green > blue * 1.12 + 8)
        & (np.abs(red.astype(np.int32) - green.astype(np.int32)) <= 92)
        & (lum >= 78)
    )
    selected = cyan | green_light | yellow

    out = np.zeros(arr.shape, dtype=np.uint8)
    out[cyan, 0] = 80
    out[cyan, 1] = 210
    out[cyan, 2] = 255
    out[green_light, 0] = 92
    out[green_light, 1] = 230
    out[green_light, 2] = 118
    out[yellow, 0] = 255
    out[yellow, 1] = 214 if target in ("advanced-cargo-wagon", "advanced-fluid-wagon") else 212
    out[yellow, 2] = 92 if target in ("advanced-cargo-wagon", "advanced-fluid-wagon") else 78

    glow_alpha = np.zeros(alpha.shape, dtype=np.uint8)
    scaled_alpha = np.clip((alpha.astype(np.float32) * 0.24).astype(np.uint16), 18, 74).astype(np.uint8)
    glow_alpha[selected] = scaled_alpha[selected]
    out[:, :, 3] = glow_alpha

    image = Image.fromarray(out)
    filtered_alpha = image.getchannel("A")
    base_alpha = source.getchannel("A").point(lambda value: 255 if value >= 8 else 0)
    filtered_alpha = ImageChops.multiply(filtered_alpha, base_alpha)
    color = image.filter(ImageFilter.GaussianBlur(0.25))
    color.putalpha(filtered_alpha)
    return color, int(np.count_nonzero(selected)), int(np.count_nonzero(opaque))


def derive_sheet(target: str, target_dir: Path, layer: str, role: str, metadata: Metadata) -> dict[str, float | int]:
    total_selected = 0
    total_opaque = 0
    expected_size = (metadata.width * metadata.line_length, metadata.height * metadata.lines_per_file)

    for file_index in range(metadata.file_count):
        source_path = target_dir / f"{layer}-{file_index}.png"
        with Image.open(source_path).convert("RGBA") as source:
            if source.size != expected_size:
                raise ValueError(f"{source_path}: size={source.size}, expected={expected_size}")
            if role == "mask":
                derived, selected, opaque = derive_mask_image(source)
            else:
                derived, selected, opaque = derive_glow_image(source, target)
            total_selected += selected
            total_opaque += opaque

        derived.save(target_dir / f"{layer}-{role}-{file_index}.png")

    digest = source_hash(target_dir, layer, metadata)
    write_metadata(
        target_dir / f"{layer}.lua",
        target_dir / f"{layer}-{role}.lua",
        layer,
        role,
        digest,
    )
    return {
        "selected_pixels": total_selected,
        "opaque_pixels": total_opaque,
        "selected_fraction": round(total_selected / total_opaque, 6) if total_opaque else 0,
    }


def crop_cell(sheet: Image.Image, metadata: Metadata, local_index: int) -> Image.Image:
    sprites_per_file = metadata.line_length * metadata.lines_per_file
    local_index = local_index % sprites_per_file
    col = local_index % metadata.line_length
    row = local_index // metadata.line_length
    left = col * metadata.width
    top = row * metadata.height
    return sheet.crop((left, top, left + metadata.width, top + metadata.height))


def load_preview_cell(
    source_dir: Path,
    cache: dict[tuple[str, int], Image.Image],
    layer: str,
    metadata: Metadata,
    index: int,
) -> Image.Image:
    sprites_per_file = metadata.line_length * metadata.lines_per_file
    file_index = index // sprites_per_file
    if file_index >= metadata.file_count:
        raise ValueError(f"{layer}: frame {index} exceeds {metadata.sprite_count} sprites")
    key = (layer, file_index)
    if key not in cache:
        cache[key] = Image.open(source_dir / f"{layer}-{file_index}.png").convert("RGBA")
    return crop_cell(cache[key], metadata, index % sprites_per_file)


def make_preview(repo: Path, preview_dir: Path, target: str, layer: str, roles: tuple[str, ...], metadata: Metadata) -> None:
    source_dir = repo / TARGETS[target]
    indices = (0, 32, 64, 96, 128, 160, 192, 224) if layer == "body" else (0, 4, 40, 44, 80, 84, 120, 124)
    cell_w = metadata.width
    cell_h = metadata.height
    rows = 2 + len(roles)
    cols = len(indices)
    sheet = Image.new("RGBA", (cols * cell_w, rows * cell_h), (0, 0, 0, 0))
    draw = ImageDraw.Draw(sheet)

    opened: dict[tuple[str, int], Image.Image] = {}
    try:
        for col, index in enumerate(indices):
            base = load_preview_cell(source_dir, opened, layer, metadata, index)
            sheet.alpha_composite(base, (col * cell_w, 0))
            overlay = base.copy()
            for role in roles:
                derived_layer = f"{layer}-{role}"
                cell = load_preview_cell(source_dir, opened, derived_layer, metadata, index)
                sheet.alpha_composite(cell, (col * cell_w, (1 + roles.index(role)) * cell_h))
                overlay.alpha_composite(cell)
            sheet.alpha_composite(overlay, (col * cell_w, (rows - 1) * cell_h))
            draw.text((col * cell_w + 4, 4), str(index), fill=(255, 255, 255, 220))
    finally:
        for image in opened.values():
            image.close()

    preview_dir.mkdir(parents=True, exist_ok=True)
    sheet.save(preview_dir / f"{target}-{layer}-accent-contact.png")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--repo", type=Path, default=Path("."), help="Repository root.")
    parser.add_argument(
        "--preview-dir",
        type=Path,
        default=Path("output/meshy/nuclear-trains/accent-previews"),
        help="Directory for diagnostic contact sheets.",
    )
    parser.add_argument(
        "--target",
        choices=sorted(TARGETS),
        action="append",
        help="Limit derivation to one or more targets. Defaults to every target.",
    )
    args = parser.parse_args()
    repo = args.repo.resolve()
    selected_targets = set(args.target or TARGETS.keys())

    for target, relative_dir in TARGETS.items():
        if target not in selected_targets:
            continue
        target_dir = repo / relative_dir
        print(f"deriving {target}: {target_dir}")
        for layer, roles in LAYER_SPECS[target].items():
            metadata = parse_metadata(target_dir / f"{layer}.lua")
            for role in roles:
                stats = derive_sheet(target, target_dir, layer, role, metadata)
                print(
                    f"  {layer}-{role}: selected={stats['selected_pixels']} "
                    f"opaque={stats['opaque_pixels']} fraction={stats['selected_fraction']}"
                )
            make_preview(repo, repo / args.preview_dir, target, layer, roles, metadata)


if __name__ == "__main__":
    main()
