"""Pack128 static directions into two4K sheets per pass and exact named anchors."""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import sys

from PIL import Image


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--bundle', required=True, type=Path)
    parser.add_argument('--output', required=True, type=Path)
    parser.add_argument('--preview', action='store_true')
    args = parser.parse_args()
    manifest = json.loads((args.bundle/'factorio-preset-render-manifest.json').read_text())
    source_count = manifest['directions']
    assert source_count == (8 if args.preview else 128)
    assert manifest['animation_frames'] == 1
    framing = manifest['preflight']
    count = framing['anisetron_direction_count']
    assert count == 128
    scale = framing['anisetron_sprite_scale']
    for folder in ('graphics/entities/anisetron', 'graphics/items', 'graphics/technology'):
        (args.output/folder).mkdir(parents=True, exist_ok=True)
    roles = {'anisetron': 'Object', 'anisetron_shadow': 'Shadow',
             'anisetron_glow': 'Light A Reduced', 'anisetron_mask': 'ColorMask'}
    rows, sheets = [], {}
    for name, folder in roles.items():
        images = [Image.open(args.bundle/folder/f'{i+1:04}.png').convert('RGBA') for i in range(source_count)]
        sheets[name] = []
        for part in range(2):
            sheet = Image.new('RGBA', (4096, 4096))
            filename = f'{name}_{part+1}.png'
            for local in range(64):
                direction = part*64+local
                index = int(direction/16+.5)%8 if args.preview else direction
                image = images[index]
                assert image.size == (512, 512)
                bounds = image.getchannel('A').getbbox()
                margin = min(bounds[0], bounds[1], 512-bounds[2], 512-bounds[3]) if bounds else None
                if bounds:
                    assert margin >= 16, (name, direction, bounds)
                elif name != 'anisetron_mask':
                    raise AssertionError(f'Empty {name} direction{direction}')
                sheet.paste(image, ((local%8)*512, (local//8)*512))
                rows.append({'role': name, 'direction': direction, 'source_direction': index,
                             'sheet': filename, 'alpha_bounds': bounds, 'margin': margin})
            sheet.save(args.output/'graphics/entities/anisetron'/filename)
            sheets[name].append(filename)
    anchors = framing['anisetron_anchor_pixels']
    lookup = {}
    for name, points in anchors.items():
        assert len(points) == count
        lookup[name] = [[i/count, [(point['anchor'][j]-point['pivot'][j])*scale/32
                                 for j in range(2)]] for i, point in enumerate(points)]
    front_index = source_count//2
    front = Image.open(args.bundle/'Object'/f'{front_index+1:04}.png').convert('RGBA')
    for folder in ('Light A Reduced', 'ColorMask'):
        front = Image.alpha_composite(front, Image.open(args.bundle/folder/f'{front_index+1:04}.png').convert('RGBA'))
    bounds = front.getchannel('A').getbbox()
    icon = front.crop(bounds)
    vehicle_source = args.output/'vehicle-icon-source.png'
    icon.save(vehicle_source)
    # Charge art comes from the original facade crystal around its measured
    # source anchor, with the pure crystal pass providing its transparent alpha.
    x, y = anchors['facade'][count//2]['anchor']
    box = (round(x-28), round(y-34), round(x+28), round(y+34))
    charge = front.crop(box)
    alpha = Image.open(args.bundle/'Light A Reduced'/f'{front_index+1:04}.png').convert('RGBA').getchannel('A').crop(box)
    charge.putalpha(alpha)
    nonempty = charge.getchannel('A').getbbox()
    assert nonempty, 'Measured facade icon crop is empty'
    charge = charge.crop(nonempty)
    charge_source = args.output/'charge-icon-source.png'
    charge.save(charge_source)
    helper = Path('.codex/skills/esir-item-icon-prep/scripts/build_factorio_item_icon.py')
    for name, path in (('anisetron', vehicle_source), ('anisetron-crystal-charge', charge_source)):
        subprocess.run([sys.executable, str(helper), '--source', str(path), '--output',
                        str(args.output/'graphics/items'/f'{name}.png'), '--preview',
                        str(args.output/f'{name}-preview.png')], check=True)
    tech = Image.new('RGBA', (256, 256))
    subject = icon.copy()
    subject.thumbnail((232, 232), Image.Resampling.LANCZOS)
    tech.alpha_composite(subject, ((256-subject.width)//2, (256-subject.height)//2))
    tech.save(args.output/'graphics/technology/anisetron.png')
    lua = ['-- blueprint: .codex/esir/blueprints/anisetron.md#contract',
           '-- Generated by the reviewed reference17 packer; clockwise128 directions.',
           '-- Projected anchors: native beam sources inherit hover/bob. Script decorations',
           '-- use the empirical lift curve in anisetron-visual-config instead.',
           'local anchors = {']
    for name, points in lookup.items():
        lua.append(f'    {name} = {{')
        lua.extend('        {%.9f, {%.9f, %.9f}},'%(orientation, *point) for orientation, point in points)
        lua.append('    },')
    lua.append('}')
    lua.extend(['return {direction_count = 128, frame_size = 512, scale = %.9f,'%scale,
                '    line_length = 8, lines_per_file = 8, slice = 8, sheets_per_pass = 2,',
                '    -- Calibrated extra bob offset for LuaRendering entity attachments; native hover is already applied.',
                '    render_attachment_lift = 0.625,',
                '    anchors = anchors, crown = anchors.top_crystal, facade = anchors.facade, muzzle = anchors.facade,',
                '    keel_tips = {anchors.keel_left, anchors.keel_center, anchors.keel_right},',
                '}'])
    (args.output/'anisetron-graphics.lua').write_text('\n'.join(lua)+'\n', encoding='utf-8')
    hashes = {str(path.relative_to(args.output)): hashlib.sha256(path.read_bytes()).hexdigest()
              for path in (args.output/'graphics').rglob('*.png')}
    report = {'preview': args.preview, 'directions': count, 'source_directions': source_count,
              'frame_size': 512, 'scale': scale, 'shift': [0, 0], 'sheet_layout': [8, 8],
              'sheets_per_pass': 2, 'filenames': sheets, 'line_length': 8, 'lines_per_file': 8,
              'slice': 8, 'anchor_lookup': lookup, 'alpha': rows, 'sha256': hashes}
    report['render_attachment_lift'] = .625
    (args.output/'asset-qc.json').write_text(json.dumps(report, indent=2), encoding='utf-8')
    print(json.dumps({'output': str(args.output), 'preview': args.preview, 'directions': count,
                      'source_directions': source_count, 'shipping_pngs': len(hashes),
                      'minimum_margin': min(row['margin'] for row in rows if row['margin'] is not None)}))


if __name__ == '__main__':
    main()
