data:extend({
  {
    type = "virtual-signal",
    name = "kr-attention-1",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/attention-1.png",
    subgroup = "kr-special-signals",
    order = "a[special-signals]-1[attention-1]",
  },
  {
    type = "virtual-signal",
    name = "kr-attention-2",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/attention-2.png",
    subgroup = "kr-special-signals",
    order = "a[special-signals]-2[attention-2]",
  },
  {
    type = "virtual-signal",
    name = "kr-attention-3",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/attention-3.png",
    subgroup = "kr-special-signals",
    order = "a[special-signals]-3[attention-3]",
  },
  {
    type = "virtual-signal",
    name = "kr-battery",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/battery.png",
    subgroup = "kr-special-signals",
    order = "a[special-signals]-a[battery]",
  },
  {
    type = "virtual-signal",
    name = "kr-battery-low",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/battery-low.png",
    subgroup = "kr-special-signals",
    order = "a[special-signals]-b[battery-low]",
  },
  {
    type = "virtual-signal",
    name = "kr-biohazard",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/biohazard.png",
    subgroup = "kr-special-signals",
    order = "a[special-signals]-6[biohazard]",
  },
  {
    type = "virtual-signal",
    name = "kr-build-here",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/build-here.png",
    subgroup = "kr-special-signals-2",
    order = "a[special-signals]-1[build-here]",
  },
  {
    type = "virtual-signal",
    name = "kr-dont-touch",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/dont-touch.png",
    subgroup = "kr-special-signals-2",
    order = "a[special-signals]-2[dont-touch]",
  },
  {
    type = "virtual-signal",
    name = "kr-energy-1",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/energy-1.png",
    subgroup = "kr-special-signals",
    order = "a[special-signals]-e[energy-1]",
  },
  {
    type = "virtual-signal",
    name = "kr-energy-2",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/energy-2.png",
    subgroup = "kr-special-signals",
    order = "a[special-signals]-e[energy-2]",
  },
  {
    type = "virtual-signal",
    name = "kr-gear-b",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/gear-b.png",
    subgroup = "kr-special-signals",
    order = "a[special-signals]-h[gear-b]",
  },
  {
    type = "virtual-signal",
    name = "kr-gear-w",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/gear-w.png",
    subgroup = "kr-special-signals",
    order = "a[special-signals]-g[gear-w]",
  },
  {
    type = "virtual-signal",
    name = "kr-heart",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/heart.png",
    subgroup = "kr-special-signals-2",
    order = "a[special-signals]-5[heart]",
  },
  {
    type = "virtual-signal",
    name = "kr-kill",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/kill.png",
    subgroup = "kr-special-signals-2",
    order = "a[special-signals]-3[kill]",
  },
  {
    type = "virtual-signal",
    name = "kr-krastorio",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/krastorio.png",
    subgroup = "kr-special-signals-2",
    order = "a[special-signals]-zzz[krastorio]",
  },
  {
    type = "virtual-signal",
    name = "kr-nuclear-1",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/nuclear-1.png",
    subgroup = "kr-special-signals",
    order = "a[special-signals]-4[nuclear-1]",
  },
  {
    type = "virtual-signal",
    name = "kr-nuclear-2",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/nuclear-2.png",
    subgroup = "kr-special-signals",
    order = "a[special-signals]-5[nuclear-2]",
  },
  {
    type = "virtual-signal",
    name = "kr-power",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/power.png",
    subgroup = "kr-special-signals",
    order = "a[special-signals]-7[power]",
  },
  {
    type = "virtual-signal",
    name = "kr-power-off",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/power-off.png",
    subgroup = "kr-special-signals",
    order = "a[special-signals]-9[power-off]",
  },
  {
    type = "virtual-signal",
    name = "kr-power-on",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/power-on.png",
    subgroup = "kr-special-signals",
    order = "a[special-signals]-8[power-on]",
  },
  {
    type = "virtual-signal",
    name = "kr-question-mark",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/question-mark.png",
    subgroup = "kr-special-signals-2",
    order = "a[special-signals]-www[question-mark]",
  },
  {
    type = "virtual-signal",
    name = "kr-recycling",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/recycling.png",
    subgroup = "kr-special-signals",
    order = "a[special-signals]-i[recycling]",
  },
  {
    type = "virtual-signal",
    name = "kr-scull",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/scull.png",
    subgroup = "kr-special-signals-2",
    order = "a[special-signals]-zz9[scull]",
  },
  {
    type = "virtual-signal",
    name = "kr-smile",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/smile.png",
    subgroup = "kr-special-signals-2",
    order = "a[special-signals]-zz9[smile]",
  },
  {
    type = "virtual-signal",
    name = "kr-star-b",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/star-b.png",
    subgroup = "kr-special-signals",
    order = "a[special-signals]-d[star-b]",
  },
  {
    type = "virtual-signal",
    name = "kr-star-w",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/star-w.png",
    subgroup = "kr-special-signals",
    order = "a[special-signals]-c[star-w]",
  },
  {
    type = "virtual-signal",
    name = "kr-time",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/time.png",
    subgroup = "kr-special-signals",
    order = "a[special-signals]-f[time]",
  },
  {
    type = "virtual-signal",
    name = "kr-wtf",
    icon = "__exotic-space-industries-graphics-3__/K2_ASSETS/icons/virtual-signals/wtf.png",
    subgroup = "kr-special-signals-2",
    order = "a[special-signals]-4[wtf]",
  },
})
