-- Generated by derive-accent-layers.py from body.lua
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 8,
  ["height"] = 530,
  ["line_length"] = 4,
  ["lines_per_file"] = 8,
  ["scale"] = 0.5,
  ["shift"] = {0 / 64, -58 / 64},
  ["sprite_count"] = 256,
  ["width"] = 526,
  ["derived_role"] = "glow",
  ["source_layer"] = "body",
  ["source_sha256"] = "23cda24f54266690d587be8d79589bc5eb073239a21aef03add97d72edaeb2b1",
}
