-- Generated by derive-accent-layers.py from sloped.lua
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 8,
  ["height"] = 612,
  ["line_length"] = 4,
  ["lines_per_file"] = 5,
  ["scale"] = 0.5,
  ["shift"] = {0 / 64, -19 / 64},
  ["sprite_count"] = 160,
  ["width"] = 572,
  ["derived_role"] = "glow",
  ["source_layer"] = "sloped",
  ["source_sha256"] = "71325837b6ee6ff08e772357bc2174a982fd3755dd058a72180af418c5c0c5a4",
}
