-- Generated by spritter v1.8.1 - https://github.com/fgardt/factorio-spritter
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 8,
  ["height"] = 612,
  ["line_length"] = 4,
  ["lines_per_file"] = 5,
  ["scale"] = 0.5,
  ["shift"] = {0 / 64, -19 / 64},
  ["sprite_count"] = 160,
  ["width"] = 572,
}
