"""Extract lance records from a large, pretty-printed Factorio data.raw dump.

Stream whole prototype records rather than loading the multi-gigabyte dump.
The dump must be nonempty, generated by Factorio2.0.77 after the final data pass.
"""
import argparse
import json
from pathlib import Path

p=argparse.ArgumentParser(description=__doc__)
p.add_argument('dump',type=Path)
p.add_argument('--output',type=Path,default=Path('.factorio-qc/angular/final-prototypes.json'))
a=p.parse_args()
assert a.dump.stat().st_size>0
name='ei-singularity-lance'
techs={name}|{name+'-'+x for x in ['axial-rupture','wound-memory','terminal-collapse','black-hole-testament']}
rows={}
kind=None
with a.dump.open(encoding='utf-8-sig') as stream:
    for line in stream:
        if line.startswith('  "') and not line.startswith('   '):
            kind=json.loads(line.strip().removesuffix(':').strip())
        if kind not in ['technology','electric-turret'] or not line.startswith('    "') or line.startswith('     '): continue
        key=json.loads(line.strip().removesuffix(':').strip())
        if key not in (techs if kind=='technology' else {name}): continue
        block=[line]
        for part in stream:
            block.append(part)
            if part.startswith('    }'):
                break
        value=json.loads('{'+''.join(block).rstrip().removesuffix(',')+'}')[key]
        if kind=='technology':
            rows[key]={'prerequisites':value.get('prerequisites'), 'unit':value.get('unit')}
        else:
            attack=value['attack_parameters']; energy=value['energy_source']
            rows['native']={'range':attack['range'],'cooldown':attack['cooldown'],
                'energy_consumption':attack['ammo_type']['energy_consumption'],
                'buffer_capacity':energy['buffer_capacity'],'input_flow_limit':energy['input_flow_limit'],'drain':energy['drain']}
assert set(rows)==techs|{'native'},rows.keys()
assert rows['native']['range']==85 and rows['native']['cooldown']==1
a.output.write_text(json.dumps({'dump':str(a.dump),'records':rows},ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
print(json.dumps(rows,ensure_ascii=False))
