-- Generated by derive-accent-layers.py from body.lua
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 8,
  ["height"] = 448,
  ["line_length"] = 4,
  ["lines_per_file"] = 8,
  ["scale"] = 0.5,
  ["shift"] = {0 / 64, -64 / 64},
  ["sprite_count"] = 256,
  ["width"] = 484,
  ["derived_role"] = "mask",
  ["source_layer"] = "body",
  ["source_sha256"] = "18252fab7c8896bf86680d3ad37243534ac9c043d2a9a430b1c05b3db6a82dc3",
}
