-- Generated by derive-accent-layers.py from sloped.lua
return {
  ["spritter"] = { 1, 8, 1 },
  ["file_count"] = 8,
  ["height"] = 548,
  ["line_length"] = 4,
  ["lines_per_file"] = 5,
  ["scale"] = 0.5,
  ["shift"] = {-0.5 / 64, -27 / 64},
  ["sprite_count"] = 160,
  ["width"] = 517,
  ["derived_role"] = "mask",
  ["source_layer"] = "sloped",
  ["source_sha256"] = "ced7f87fc9ed953efb4f6968776ea7eed4c219eade42e8ca7143ca713b4066cc",
}
